### ISSUE TITLE
Inventory blank boxes 

### ISSUE THREAD

**Issue by anunezgtr** [DokusCore/DokusCore--Inventory#3]
Hi, I have played around a bit(with the configs) before submitting this and I cannot figure out why the inventory is blank... 

![blank inventory](https://user-images.githubusercontent.com/45487153/202831108-d9f6fcb1-b29d-42df-9fc3-82cf7c274d47.png)

**Comment by BulletCatcher82** [comment]
I´ve got exactly the same issue, isn´t there a solution yet?

**Comment by DevDokus** [comment]
This issue has been fixed in the update that has been pushed a couple of minutes ago. The problem was that the folder that holds the inventory item pictures was capitalized while it should not have been. The pictures should load correctly now.
